version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - call dev_scripts\install_dependencies.cmd
  - call dev_scripts\build_game.cmd
  - call dev_scripts\package_game.cmd

artifacts:
- path: dev_scripts\DIST\imgi_demo_linux.tar.gz
  name: imgi_demo_linux.tar.gz
- path: dev_scripts\DIST\imgi_demo_windows.zip
  name: imgi_demo_windows.zip
- path: imgi.scm
  name: imgi.scm
  
deploy:
- provider: GitHub
  auth_token:
    secure: wZdCrU9dcec59hLKrRi7G6N4mWamWoDHcGTe4T2P5YJsV7CEYCyEcDwulO0V3bzK
  artifact: imgi.scm, imgi_demo_linux.tar.gz, imgi_demo_windows.zip
  draft: false
  prerelease: false
  force_update: true          # it can't edit a release artifact if this is false
  on:
    branch: main              # release from main branch only
    appveyor_repo_tag: true   # deploy on tag push only